version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Pasamos las variables de entorno para que Vite pueda hacer el build con ellas
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    restart: unless-stopped
    ports:
      - "80:80"
    # Opcional: Define las variables de entorno en el contenedor (Nginx no las necesita realmente pero es buena práctica)
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
